# Generated by Django 3.0.6 on 2020-06-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='service',
            field=models.CharField(default='Wax & Wash', max_length=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='staff',
            field=models.CharField(default='Junior', max_length=100),
        ),
    ]
